blank_issues_enabled: false

contact_links:
  - name: ğŸ“Œ GonggakSim ë°±ì—”ë“œ ì´ìŠˆ ê°€ì´ë“œ
    url: https://github.com/GonggakSim/Backend/issues
    about: ì¼ë°˜ì ì¸ ë¬¸ì˜ë‚˜ ë²„ê·¸ ë¦¬í¬íŠ¸ ì „ì— ì´ìŠˆ ê°€ì´ë“œë¥¼ í™•ì¸í•´ì£¼ì„¸ìš”.

issue_templates:
  - name: ğŸ ë²„ê·¸ ë¦¬í¬íŠ¸
    description: ë²„ê·¸ë¥¼ ì‹ ê³ í•˜ê³  ìˆ˜ì • ìš”ì²­ì„ ì‘ì„±í•˜ì„¸ìš”.
    file: bug_report.md

  - name: âœ¨ ê¸°ëŠ¥ ìš”ì²­
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ì„ ì œì•ˆí•˜ì„¸ìš”.
    file: feature_request.md